---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - ckh.io
  resources:
  - ckhs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ckh.io
  resources:
  - ckhs/status
  verbs:
  - get
  - patch
  - update
