-- The event table: one row per alert notification the pipeline has accepted.
--
-- Applied at startup by store.Migrate when ALERTPROCESSOR_DB_AUTO_MIGRATE=true,
-- and safe to run by hand (the Supabase SQL editor works) when it is false.
-- Every statement is idempotent, because "run it again" is the recovery path.
--
-- This file is the schema's single source of truth. The Go constants in
-- internal/event must agree with the CHECK below; TestStatusesMatchMigration
-- reads this file and fails if they drift.

CREATE TABLE IF NOT EXISTS event (
    -- Generated by the service, not the database, so the value is known before
    -- the INSERT and can go into the RabbitMQ message's message_id without a
    -- round trip.
    event_id      UUID        PRIMARY KEY,

    -- Alertmanager's fingerprint: stable for as long as the alert keeps the
    -- same label set. Many events share one alert_id over an alert's life.
    alert_id      TEXT        NOT NULL,

    -- What the harness has done about this event. This service only ever writes
    -- 'waiting'; the rest of the vocabulary belongs to harness/ and is declared
    -- here so there is one definition of it.
    status        TEXT        NOT NULL DEFAULT 'waiting',

    -- What Prometheus says about the world, as distinct from `status` above. An
    -- alert can be resolved while its event is still being worked on.
    alert_status  TEXT        NOT NULL,

    alert_name    TEXT        NOT NULL,
    severity      TEXT,
    namespace     TEXT,
    -- Most specific object the labels name, kind-qualified: 'pod/web-0'.
    resource      TEXT,

    summary       TEXT,
    description   TEXT,
    runbook_url   TEXT,
    generator_url TEXT,

    starts_at     TIMESTAMPTZ NOT NULL,
    ends_at       TIMESTAMPTZ,

    labels        JSONB       NOT NULL DEFAULT '{}'::jsonb,
    annotations   JSONB       NOT NULL DEFAULT '{}'::jsonb,
    -- The alert exactly as received, so an event can be reinterpreted after the
    -- projection above changes without re-firing the alert.
    raw_alert     JSONB       NOT NULL DEFAULT '{}'::jsonb,

    received_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- NULL until RabbitMQ confirms the message. A row with published_at NULL is
    -- recorded but not yet handed off -- the state a replay job would look for.
    published_at  TIMESTAMPTZ,

    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- A CHECK rather than a PostgreSQL ENUM: adding a status later is an UPDATE
    -- to this constraint, where an ENUM would need ALTER TYPE, which cannot run
    -- inside a transaction on older servers and is awkward to make idempotent.
    CONSTRAINT event_status_valid CHECK (status IN (
        'waiting',
        'solving',
        'waiting_human_approval',
        'resolved',
        'failed_to_resolve'
    )),
    CONSTRAINT event_alert_status_valid CHECK (alert_status IN ('firing', 'resolved'))
);

-- The deduplication key, and the reason this pipeline is safe to retry.
--
-- Alertmanager retries a failed webhook and re-notifies every repeat_interval,
-- so the same notification arrives repeatedly. This index makes those arrivals
-- collide on an existing row instead of creating work twice.
--
-- The three columns are chosen so that genuinely new events still get through:
--   alert_id      -- different alert, different event
--   alert_status  -- the same alert resolving IS a new event
--   starts_at     -- the same alert firing again after resolving IS a new event
--
-- Widening this tuple (adding received_at, say) silently disables deduplication.
-- Narrowing it (dropping alert_status) silently swallows resolutions.
CREATE UNIQUE INDEX IF NOT EXISTS event_notification_key
    ON event (alert_id, alert_status, starts_at);

-- The harness's read path: "what is waiting for me, oldest first".
CREATE INDEX IF NOT EXISTS event_status_received_idx
    ON event (status, received_at DESC);

-- Finding rows that were recorded but never handed off, for a replay job.
-- Partial, so it stays small: in a healthy system almost every row is published.
CREATE INDEX IF NOT EXISTS event_unpublished_idx
    ON event (received_at)
    WHERE published_at IS NULL;

-- Alert history for one alert, newest first.
CREATE INDEX IF NOT EXISTS event_alert_id_idx
    ON event (alert_id, received_at DESC);
